name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore GooseNet/GooseNetSolution.sln
    - name: Build
      run: dotnet build GooseNet/GooseNetSolution.sln --no-restore
    - name: Test
      run: dotnet test GooseNet/GooseNetSolution.sln --no-build --verbosity normal
