name: GooseNetBuild

on:
  push:
    branches: [ "master", "primary_testing" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup Checkoutv3
    - uses: actions/checkout@v3

    - name: MSBuild Version Test
      run: C:\'Program Files'\'Microsoft Visual Studio'\2022\Enterprise\Msbuild\Current\Bin\MSBuild.exe --version

    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v2
    #  with:
    #    dotnet-version: 6.0.x
        
    
    #- name: Restore
    #  run: dotnet restore GooseNet.csproj
    #- name: Build
    #  run: dotnet build GooseNet.csproj --no-restore
    #- name: Test
    #  run: dotnet test GooseNet.csproj --no-build --verbosity normal
